services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  backend-dev:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/task
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    command: ["app.handler"]

  backend-test:
    image: lambci/lambda:nodejs18.x
    volumes:
      - ./backend:/var/task
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    command: ["app.handler", "-e", "event.json"]

  diary-converter:
    build:
      context: ./tools/diary-converter
    volumes:
      - ./tools/diary-converter:/app
      - ./Documents/ProjectLogs:/app/input
      - ./articles:/app/output
    environment:
      - GOOGLE_API_KEY
    working_dir: /app
    # コマンドは実行時に引数として渡す
    # 例: docker-compose run diary-converter input/2025-03-10-Claude-Cursor連携開発.md output/2025-03-10-claude-cursor.md
