services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  backend-dev:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/task
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    command: ["app.handler"]

  backend-test:
    image: lambci/lambda:nodejs18.x
    volumes:
      - ./backend:/var/task
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    command: ["app.handler", "-e", "event.json"]