name: 'Diary Converter'
description: 'Convert development diary logs to Zenn articles'
author: '[username]'

inputs:
  source_file:
    description: 'Path to the source diary file'
    required: true
  destination_file:
    description: 'Path to the destination article file'
    required: true
  api_key:
    description: 'Gemini API Key'
    required: true
  model:
    description: 'Gemini model to use'
    required: false
    default: 'gemini-2.0-flash-001'
  template:
    description: 'Template file path'
    required: false
    default: './templates/zenn_template.md'
  cycle_article:
    description: 'URL to development cycle article'
    required: false
    default: ''
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Prepare output directory
      run: |
        mkdir -p $(dirname ${{ inputs.destination_file }})
      shell: bash

    - name: Run Diary Converter
      run: |
        cd ${{ github.action_path }}
        
        DEBUG_FLAG=""
        if [ "${{ inputs.debug }}" = "true" ]; then
          DEBUG_FLAG="--debug"
        fi
        
        TEMPLATE_ARG=""
        if [ -n "${{ inputs.template }}" ]; then
          if [[ "${{ inputs.template }}" == /* ]]; then
            # Absolute path
            TEMPLATE_ARG="--template ${{ inputs.template }}"
          else
            # Relative path
            TEMPLATE_ARG="--template ${{ github.workspace }}/${{ inputs.template }}"
          fi
        fi
        
        CYCLE_ARTICLE_ARG=""
        if [ -n "${{ inputs.cycle_article }}" ]; then
          CYCLE_ARTICLE_ARG="--cycle-article ${{ inputs.cycle_article }}"
        fi
        
        export GOOGLE_API_KEY="${{ inputs.api_key }}"
        
        echo "Converting ${{ inputs.source_file }} to ${{ inputs.destination_file }}"
        echo "Using model: ${{ inputs.model }}"
        
        python diary_converter.py \
          "${{ github.workspace }}/${{ inputs.source_file }}" \
          "${{ github.workspace }}/${{ inputs.destination_file }}" \
          --model "${{ inputs.model }}" \
          $DEBUG_FLAG $TEMPLATE_ARG $CYCLE_ARTICLE_ARG
      shell: bash

    - name: Verify Output
      run: |
        if [ -f "${{ github.workspace }}/${{ inputs.destination_file }}" ]; then
          echo "✅ Conversion successful: ${{ inputs.destination_file }}"
          wc -l "${{ github.workspace }}/${{ inputs.destination_file }}"
        else
          echo "❌ Conversion failed: File not created"
          exit 1
        fi
      shell: bash

branding:
  icon: 'book'
  color: 'blue' 