name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  zenn-deploy: # Zenn deploy job を追加
    runs-on: ubuntu-latest
    needs: frontend-deploy # frontend-deploy job の完了後に実行
    steps:
      - name: Checkout code # コードをチェックアウト
        uses: actions/checkout@v2

      - name: Setup Node.js # Node.js をセットアップ
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Zenn CLI が Node.js 環境で動作するため

      - name: Install zenn-cli # zenn-cli をインストール
        run: npm install -g zenn-cli

      - name: Zenn Publish # Zenn に публикацииを実行
        working-directory: Documents/articles # Zenn の記事があるディレクトリを指定
        run: zenn articles publish # articles ディレクトリにある記事を публикации

  backend-deploy:
    runs-on: ubuntu-latest
    needs: zenn-deploy # zenn-deploy job の完了後に実行 (backend は zenn-deploy に依存)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          zip -r function.zip .
          aws lambda update-function-code --function-name your-lambda-function-name --zip-file fileb://function.zip
