name: Minimal GitHub Pages Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build frontend
        run: |
          ls -R frontend
          mkdir -p frontend/build
          cp frontend/*.html frontend/build/
          cp frontend/*.css frontend/build/
          cp frontend/*.js frontend/build/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
